name: Release GitHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install-ci-test
      - run: npm run build
      - run: npm run package
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            *.vsix
            LICENSE